# Generated by Django 3.0.5 on 2020-04-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
